name: Build Mac App
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest  # Menggunakan versi terbaru yang pasti didukung
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install Dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install pyinstaller midiutil
        
    - name: Build Mac App
      run: |
        python3 -m PyInstaller --windowed --onefile --name "Type_Text_To_Midi" type_text_to_midi_pro.py
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4 # Versi 4 lebih cepat dan stabil
      with:
        name: Mac-App-Result
        path: dist/Type_Text_To_Midi.app
